repos:
  ###### FORMATTING ######
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  ###### LINTING ######
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.4
  #   hooks:
  #     - id: bandit
  #       args: ["--configfile", ".bandit", "--baseline", "tests/known_issues.json"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
      # any flake8 plugins must be included in the hook venv
      # additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: mixed-line-ending
        args: [--fix=no]

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-eval
      # - id: rst-backticks
      # - id: rst-directive-colons
      # - id: rst-inline-touching-normal
